language: go

go:
  - "1.11.x"
  - master

# Force-enable Go modules. Also force go to use the code in vendor/
# These will both be unnecessary when Go 1.13 lands.
env:
  global:
    - secure: "AgSMfSShtZFz7Kqs98XjMSTHqyaL3CqTg5t/9Dg9iCNTli0zzD/M+pqM6h8Hb5/Zp1SjZKKrlBqRQ3rAZfmJRrOQVHrkV2iDRMwVMOZWnkD4dqvrRlv33lT5tyKx8Xz3AiDcdiMOEf35GoHI8vYqxPa/TOLIheCvp+Fb6dPKaP3ft+EijqYH3+SdxjZD9IXMv4/NRlcI/MG9eylunt707fwV/oJk2+N9VO55vkInl6bsIgJXwU8kFUSEoNsFTMkuGJ+ROCdMaLKl7ivcmhEuf0m6lOs8NqnT34FdOmp5zZOMuR38fUVJeKYtHgMaAtQkts5UUggip7B1NseDlif1tyP4JRLteb8pN61C1Ci8ecoiq6a0eRVhaVFF9WhPhgo8TZ+wkTgPtiAQ2RWzN1DrRg2O3gpWDfbWbxaJQZkLyt84XFjhk+axFS2YPd454qV4blDqD5+eZqvBEzQhCbJ6wEbXRDnxDuioBNaYFdp98ahqRUHTITGJhOPTjTnjU/g70WCxrTz2sGOlH6/al41Ka8wI2tbhwuUg0IYaMbqD++19YT+lbPXHza3FvxQkkFFi32yeIfsTDXu9aD4kyhsuObd6e16/6QlJTXfkIJT5EDKMTS6Br/mt+16TuHd81X9MRTHWuYTEpvNOqAMguDmgoBclqnjGLp9P4QPIehGfypE="
    - GO111MODULE=on

# Only clone the most recent commit.
git:
  depth: 1

# Skip the install step. Don't `go get` dependencies. Only build with the code
# in vendor/
install: true

# Don't email me the results of the test runs.
# https://docs.travis-ci.com/user/notifications/#configuring-slack-notifications
notifications:
  email: false
  # slack:
  #   on_success: always
  #   on_failure: never

before_script:
  - go get golang.org/x/lint/golint
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - golint ./... | grep -v "be unexported"
  - go test -v -race -covermode=count -coverprofile=coverage.out ./... # Run all the tests with the race detector enabled
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN || exit 0

# before_deploy:
# deploy:
#   skip_cleanup: true
# after_deploy:
